image: node:13.0.1

before_script:
  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}

# test:lint:
#   script:
#     - npm run lint
# test:node:12:
#   script:
#     - npm test

# Publish tagged versions to npm
publish:
  stage: deploy
  only:
    refs:
      - master
  script:
    - npm install
    - npm run build
    - npm publish